### ISSUE TITLE
Predictable element identifiers

### ISSUE THREAD

**Issue by michielz** [DANS-KNAW/dans-frontend-framework#91]
As a frontend tester, I need predictable/unique identifiers to select the different elements of the form. In the current situation, there is no reliable way to select fields. Without a reliable way to select the elements, tests become brittle.

For example, the name fields of the interviewee could have identifiers like: Interviewee_1_first_name, Interviewee_1_last_name. The consent checkbox should also have a unique value like Interviewee_1_consent_checkbox.

**Comment by ddzyne** [comment]
Fixed :)
